version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '2638543'
      POSTGRES_DB: 'db'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
    - '6379:6379'
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./config/redis:/usr/local/etc/redis

  api:
    build:
      context: .
    tty: false
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build:
      context: .
    environment:
      - DEBUG=1
      - SECRET_KEY=$SECRET_KEY
      - DJANGO_ALLOWED_HOSTS=['*']
      - CELERY_BEAT_SCHEDULER=$CELERY_BEAT_SCHEDULER
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - CELERY_ACCEPT_CONTENT=json
      - CELERY_TASK_SERIALIZER=json
      - CELERY_RESULT_SERIALIZER=json
    ports: []
    volumes:
      - ./project/:/usr/src/app/
    depends_on:
      redis:
        condition: service_healthy
      api:
        condition: service_healthy


volumes:
  db:
    driver: local
  redis:
    driver: local
