# Generated by Django 4.2.1 on 2023-05-05 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='место')),
                ('time', models.TimeField(default='00:00', verbose_name='время исполнения')),
                ('action', models.CharField(max_length=150, verbose_name='действие')),
                ('pleasant', models.BooleanField(default=False, verbose_name='приятная привычка')),
                ('frequency', models.IntegerField(blank=True, default=1, null=True, verbose_name='периодичность выполнения привычки')),
                ('award', models.CharField(blank=True, max_length=150, null=True, verbose_name='вознаграждение')),
                ('time_complete', models.TimeField(default='00:01', verbose_name='время на выполнение')),
                ('status_public', models.CharField(choices=[('public', 'общий доступ'), ('private', 'приватный доступ')], default='public', max_length=15, verbose_name='признак публичности')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.habit', verbose_name='связанная привычка')),
            ],
        ),
    ]
